USE job_portal;

-- First create a recruiter user to post jobs
INSERT IGNORE INTO users (email, password, full_name, role_id, is_active, is_approved)
VALUES ('recruiter@jobportal.com', '$2a$10$4L6KSV6gmaq4gRj0X9lju.8SQDuN.AphNg544Nq7jK1ecAblm/Rg.', 'Rajesh Sharma', 2, TRUE, TRUE);

-- Create recruiter profile
INSERT IGNORE INTO recruiter_profiles (user_id, company_id, position, bio)
SELECT u.id, 1, 'Senior Technical Recruiter', 'Experienced recruiter helping companies find top talent.'
FROM users u WHERE u.email = 'recruiter@jobportal.com';

-- Delete existing jobs (if any with broken references)
DELETE FROM job_skills;
DELETE FROM job_applications;
DELETE FROM saved_jobs WHERE job_id IN (SELECT id FROM jobs);
DELETE FROM jobs;

-- Now insert 30 jobs using the recruiter user
SET @recruiter_id = (SELECT id FROM users WHERE email = 'recruiter@jobportal.com');

INSERT INTO jobs (title, description, requirements, location, job_type, experience_level, salary_min, salary_max, currency, deadline, is_active, company_id, posted_by, created_at) VALUES
('Senior Full Stack Engineer', 'We are looking for a Senior Full Stack Engineer to join our core platform team. You will design and implement scalable web applications, mentor junior engineers, and drive technical decisions that impact millions of users worldwide.\n\nResponsibilities:\n• Design and build robust, scalable web applications\n• Collaborate with product managers and designers\n• Write clean, testable, and maintainable code\n• Participate in code reviews and architectural discussions', 'Requirements:\n• 5+ years of experience in full stack development\n• Strong proficiency in React, TypeScript, and Node.js\n• Experience with cloud services (AWS/GCP/Azure)\n• Understanding of microservices architecture', 'Mountain View, CA', 'FULL_TIME', 'SENIOR', 150000, 220000, 'USD', '2026-04-15', true, 1, @recruiter_id, DATE_SUB(NOW(), INTERVAL 2 DAY)),

('Machine Learning Engineer', 'Join our AI team to build next-generation ML models that power search, recommendations, and content understanding. Work with petabyte-scale data and cutting-edge research.\n\nResponsibilities:\n• Develop and deploy ML models at scale\n• Design experiments and analyze results\n• Collaborate with research scientists', 'Requirements:\n• MS/PhD in Computer Science or related field\n• 3+ years of ML engineering experience\n• Proficiency in Python, TensorFlow/PyTorch\n• Experience with large-scale distributed systems', 'Mountain View, CA', 'FULL_TIME', 'SENIOR', 180000, 280000, 'USD', '2026-05-01', true, 1, @recruiter_id, DATE_SUB(NOW(), INTERVAL 5 DAY)),

('Frontend Developer', 'Build beautiful, responsive user interfaces for our cloud products used by millions of developers worldwide.\n\nResponsibilities:\n• Build responsive web applications with React/TypeScript\n• Implement pixel-perfect designs from Figma\n• Optimize performance and accessibility\n• Write unit and integration tests', 'Requirements:\n• 3+ years of frontend development experience\n• Expert in React, TypeScript, HTML/CSS\n• Experience with state management (Redux, Zustand)\n• Knowledge of accessibility standards', 'Redmond, WA', 'FULL_TIME', 'MID', 120000, 170000, 'USD', '2026-04-20', true, 2, @recruiter_id, DATE_SUB(NOW(), INTERVAL 1 DAY)),

('Cloud Solutions Architect', 'Design and implement cloud infrastructure solutions for enterprise customers. Help organizations modernize their technology stack.\n\nResponsibilities:\n• Design cloud architecture solutions\n• Lead technical discussions with customers\n• Create reference architectures and best practices', 'Requirements:\n• 7+ years in software engineering or architecture\n• Deep knowledge of AWS/Azure/GCP\n• Experience with containerization (Docker, K8s)\n• Cloud certifications preferred', 'Seattle, WA', 'FULL_TIME', 'LEAD', 160000, 240000, 'USD', '2026-05-10', true, 3, @recruiter_id, DATE_SUB(NOW(), INTERVAL 3 DAY)),

('Data Scientist', 'Analyze large-scale user behavior data to drive content recommendations and improve the viewing experience for 200M+ subscribers.\n\nResponsibilities:\n• Build predictive models and recommendation systems\n• Design and analyze A/B experiments\n• Create dashboards and data visualizations', 'Requirements:\n• MS in Statistics, Math, or Computer Science\n• 3+ years of data science experience\n• Proficiency in Python, SQL, and R\n• Experience with recommendation systems', 'Los Gatos, CA', 'FULL_TIME', 'MID', 140000, 200000, 'USD', '2026-04-25', true, 5, @recruiter_id, DATE_SUB(NOW(), INTERVAL 4 DAY)),

('Backend Engineer - Payments', 'Build and scale the payment infrastructure that powers millions of transactions daily. Work on critical financial systems.\n\nResponsibilities:\n• Design and implement payment APIs\n• Ensure system reliability and compliance\n• Optimize transaction processing pipelines', 'Requirements:\n• 4+ years of backend development\n• Strong knowledge of Java or Ruby\n• Experience with financial systems\n• Understanding of PCI compliance', 'San Francisco, CA', 'FULL_TIME', 'MID', 145000, 210000, 'USD', '2026-05-05', true, 6, @recruiter_id, DATE_SUB(NOW(), INTERVAL 6 DAY)),

('Mobile Developer (React Native)', 'Create engaging mobile experiences for our music streaming app used by 500M+ users.\n\nResponsibilities:\n• Develop cross-platform mobile features\n• Optimize app performance and battery usage\n• Implement smooth animations and transitions', 'Requirements:\n• 3+ years of React Native development\n• Experience with iOS and Android platforms\n• Knowledge of audio/video streaming\n• Published apps in app stores', 'Stockholm, Sweden', 'FULL_TIME', 'MID', 110000, 160000, 'USD', '2026-04-30', true, 7, @recruiter_id, DATE_SUB(NOW(), INTERVAL 7 DAY)),

('DevOps Engineer', 'Build and maintain our cloud infrastructure and CI/CD pipelines. Help us scale to support millions of hosts and guests.\n\nResponsibilities:\n• Manage Kubernetes clusters and cloud infra\n• Build and optimize CI/CD pipelines\n• Implement monitoring and incident response', 'Requirements:\n• 4+ years of DevOps/SRE experience\n• Expert in Kubernetes, Docker, Terraform\n• Experience with AWS or GCP\n• Strong scripting skills (Python, Bash)', 'San Francisco, CA', 'FULL_TIME', 'MID', 130000, 190000, 'USD', '2026-05-15', true, 8, @recruiter_id, DATE_SUB(NOW(), INTERVAL 8 DAY)),

('Product Designer (UX)', 'Design intuitive and delightful user experiences for our communication platform used by millions of teams.\n\nResponsibilities:\n• Create wireframes, prototypes, and high-fidelity designs\n• Conduct user research and usability testing\n• Define design systems and component libraries', 'Requirements:\n• 4+ years of product design experience\n• Expert in Figma and design tools\n• Strong portfolio showcasing UX work\n• Experience with design systems', 'San Francisco, CA', 'FULL_TIME', 'MID', 125000, 175000, 'USD', '2026-04-28', true, 9, @recruiter_id, DATE_SUB(NOW(), INTERVAL 9 DAY)),

('E-commerce Platform Engineer', 'Help build the commerce platform that powers millions of online stores. Work on checkout, payments, and merchant tools.\n\nResponsibilities:\n• Build scalable e-commerce features\n• Optimize checkout conversion rates\n• Implement payment integrations', 'Requirements:\n• 3+ years of full stack experience\n• Proficiency in Ruby on Rails or Node.js\n• Experience with e-commerce systems\n• Knowledge of payment gateways', 'Ottawa, Canada', 'FULL_TIME', 'MID', 120000, 170000, 'USD', '2026-05-20', true, 10, @recruiter_id, DATE_SUB(NOW(), INTERVAL 10 DAY)),

('AI Research Intern', 'Join our research team for a summer internship working on Large Language Models and multimodal AI systems.\n\nResponsibilities:\n• Conduct research under senior scientists\n• Implement and evaluate ML models\n• Write research papers', 'Requirements:\n• Enrolled in MS/PhD program\n• Strong foundation in ML/DL\n• Python and PyTorch proficiency\n• Published research is a plus', 'Menlo Park, CA', 'INTERNSHIP', 'ENTRY', 8000, 12000, 'USD', '2026-03-31', true, 4, @recruiter_id, DATE_SUB(NOW(), INTERVAL 3 DAY)),

('Remote Python Developer', 'Work from anywhere on our backend services built with Django and FastAPI. Flexible schedule, async-first culture.\n\nResponsibilities:\n• Develop RESTful APIs with Python\n• Write comprehensive tests\n• Participate in async code reviews', 'Requirements:\n• 2+ years Python experience\n• Django and/or FastAPI knowledge\n• PostgreSQL proficiency\n• Good async communication skills', 'Remote', 'REMOTE', 'MID', 90000, 140000, 'USD', '2026-04-30', true, 6, @recruiter_id, DATE_SUB(NOW(), INTERVAL 2 DAY)),

('Junior Software Engineer', 'Start your career at one of the world''s top tech companies. Structured mentorship and meaningful projects from day one.\n\nResponsibilities:\n• Write clean, tested code\n• Learn from senior engineers\n• Contribute to real products', 'Requirements:\n• BS in Computer Science or equivalent\n• Proficiency in at least one language\n• Understanding of data structures/algorithms\n• Eagerness to learn and grow', 'Redmond, WA', 'FULL_TIME', 'ENTRY', 95000, 130000, 'USD', '2026-05-01', true, 2, @recruiter_id, DATE_SUB(NOW(), INTERVAL 1 DAY)),

('Part-Time UI Developer', 'Looking for a talented UI developer to work part-time on our design system. 20 hours/week, flexible schedule.\n\nResponsibilities:\n• Build reusable UI components in React\n• Maintain the design system\n• Write Storybook documentation', 'Requirements:\n• 2+ years of frontend experience\n• React and CSS expertise\n• Figma to code workflow\n• Attention to visual detail', 'Remote', 'PART_TIME', 'MID', 50000, 75000, 'USD', '2026-04-15', true, 9, @recruiter_id, DATE_SUB(NOW(), INTERVAL 5 DAY)),

('Contract Data Engineer', 'Join us for a 6-month contract to build next-generation data pipeline infrastructure.\n\nResponsibilities:\n• Design and build ETL pipelines\n• Work with Spark, Airflow, and Kafka\n• Optimize data warehouse queries', 'Requirements:\n• 4+ years data engineering experience\n• Expert in Spark and Airflow\n• SQL and Python proficiency\n• Experience with cloud data services', 'Seattle, WA', 'CONTRACT', 'SENIOR', 160000, 200000, 'USD', '2026-04-20', true, 3, @recruiter_id, DATE_SUB(NOW(), INTERVAL 6 DAY)),

('Cybersecurity Analyst', 'Protect our global infrastructure and respond to evolving cyber threats. Join our world-class security team.\n\nResponsibilities:\n• Monitor security alerts and investigate incidents\n• Conduct vulnerability assessments\n• Develop security automation tools\n• Participate in incident response', 'Requirements:\n• 3+ years in cybersecurity\n• Knowledge of SIEM tools (Splunk, ELK)\n• Understanding of network security\n• Security certifications (CISSP, CEH) preferred', 'Redmond, WA', 'FULL_TIME', 'MID', 130000, 180000, 'USD', '2026-05-01', true, 2, @recruiter_id, DATE_SUB(NOW(), INTERVAL 1 DAY)),

('Site Reliability Engineer', 'Ensure 99.99% uptime for services used by billions of people. Own the reliability of our most critical systems.\n\nResponsibilities:\n• Design and maintain highly available systems\n• Automate operational tasks\n• Lead incident response and post-mortems\n• Optimize system performance', 'Requirements:\n• 5+ years SRE/DevOps experience\n• Expert in Linux, networking, and distributed systems\n• Proficiency in Go or Python\n• Experience with Kubernetes and cloud platforms', 'Mountain View, CA', 'FULL_TIME', 'SENIOR', 170000, 250000, 'USD', '2026-04-30', true, 1, @recruiter_id, DATE_SUB(NOW(), INTERVAL 3 DAY)),

('Technical Program Manager', 'Drive cross-functional programs that ship features to millions of users. Coordinate engineering, design, and product teams.\n\nResponsibilities:\n• Manage complex multi-team projects\n• Track deliverables and remove blockers\n• Communicate status to leadership\n• Drive process improvements', 'Requirements:\n• 5+ years program management experience\n• Technical background (CS degree or equivalent)\n• Experience with Agile/Scrum methodologies\n• Excellent communication skills', 'Seattle, WA', 'FULL_TIME', 'SENIOR', 150000, 220000, 'USD', '2026-05-10', true, 3, @recruiter_id, DATE_SUB(NOW(), INTERVAL 4 DAY)),

('iOS Developer', 'Build the next generation of our iOS app used by hundreds of millions of users worldwide.\n\nResponsibilities:\n• Develop new features for iOS platform\n• Write clean, efficient Swift code\n• Collaborate with design and backend teams\n• Optimize app performance', 'Requirements:\n• 3+ years iOS development experience\n• Expert in Swift and SwiftUI\n• Experience with Core Data, URLSession\n• Published apps on App Store', 'Menlo Park, CA', 'FULL_TIME', 'MID', 140000, 200000, 'USD', '2026-04-25', true, 4, @recruiter_id, DATE_SUB(NOW(), INTERVAL 2 DAY)),

('Android Developer', 'Create amazing Android experiences for our streaming platform. Work on offline playback, performance, and accessibility.\n\nResponsibilities:\n• Develop Android features using Kotlin\n• Implement Material Design UI\n• Optimize for various screen sizes\n• Write unit and UI tests', 'Requirements:\n• 3+ years Android development\n• Expert in Kotlin and Jetpack Compose\n• Knowledge of MVVM architecture\n• Experience with media playback', 'Stockholm, Sweden', 'FULL_TIME', 'MID', 115000, 165000, 'USD', '2026-05-05', true, 7, @recruiter_id, DATE_SUB(NOW(), INTERVAL 5 DAY)),

('Database Administrator', 'Manage and optimize our mission-critical database infrastructure supporting billions of transactions.\n\nResponsibilities:\n• Administer MySQL and PostgreSQL databases\n• Performance tuning and query optimization\n• Implement backup and disaster recovery\n• Database security and access control', 'Requirements:\n• 5+ years DBA experience\n• Expert in MySQL and PostgreSQL\n• Experience with database replication\n• Knowledge of cloud database services', 'San Francisco, CA', 'FULL_TIME', 'SENIOR', 140000, 195000, 'USD', '2026-04-28', true, 6, @recruiter_id, DATE_SUB(NOW(), INTERVAL 7 DAY)),

('QA Automation Engineer', 'Build comprehensive test automation frameworks to ensure quality across our platform.\n\nResponsibilities:\n• Design and implement test automation\n• Create CI/CD integrated test suites\n• Perform API and UI testing\n• Mentor manual QA team on automation', 'Requirements:\n• 3+ years QA automation experience\n• Proficiency in Selenium, Cypress, or Playwright\n• Experience with API testing tools\n• Knowledge of CI/CD pipelines', 'Ottawa, Canada', 'FULL_TIME', 'MID', 100000, 145000, 'USD', '2026-05-12', true, 10, @recruiter_id, DATE_SUB(NOW(), INTERVAL 6 DAY)),

('Blockchain Developer', 'Build decentralized applications and smart contracts for our Web3 platform.\n\nResponsibilities:\n• Develop smart contracts in Solidity\n• Build dApps with React and ethers.js\n• Conduct security audits\n• Research new blockchain technologies', 'Requirements:\n• 2+ years blockchain development\n• Expert in Solidity and EVM\n• Experience with DeFi protocols\n• Knowledge of cryptography fundamentals', 'San Francisco, CA', 'FULL_TIME', 'MID', 150000, 220000, 'USD', '2026-04-20', true, 6, @recruiter_id, DATE_SUB(NOW(), INTERVAL 8 DAY)),

('Content Writer - Tech', 'Create compelling technical content for our developer blog and documentation.\n\nResponsibilities:\n• Write blog posts and tutorials\n• Create API documentation\n• Produce video scripts for dev content\n• Collaborate with engineering teams', 'Requirements:\n• 2+ years technical writing experience\n• Strong understanding of software concepts\n• Excellent English writing skills\n• Portfolio of published tech content', 'Remote', 'REMOTE', 'MID', 70000, 100000, 'USD', '2026-05-01', true, 1, @recruiter_id, DATE_SUB(NOW(), INTERVAL 1 DAY)),

('Staff Software Engineer', 'Lead technical initiatives across multiple teams. Define architecture and mentor senior engineers.\n\nResponsibilities:\n• Set technical direction for the org\n• Design complex distributed systems\n• Mentor senior engineers\n• Drive engineering excellence', 'Requirements:\n• 8+ years software engineering experience\n• Track record of technical leadership\n• Expert in system design\n• Experience with large-scale systems', 'San Francisco, CA', 'FULL_TIME', 'LEAD', 200000, 320000, 'USD', '2026-05-15', true, 8, @recruiter_id, DATE_SUB(NOW(), INTERVAL 4 DAY)),

('ML Ops Engineer', 'Build and maintain the infrastructure for training and deploying ML models at scale.\n\nResponsibilities:\n• Design ML training pipelines\n• Manage model serving infrastructure\n• Implement model monitoring\n• Optimize GPU utilization', 'Requirements:\n• 3+ years MLOps experience\n• Proficiency in Kubernetes and Docker\n• Experience with ML frameworks\n• Knowledge of distributed computing', 'Mountain View, CA', 'FULL_TIME', 'MID', 145000, 210000, 'USD', '2026-04-22', true, 1, @recruiter_id, DATE_SUB(NOW(), INTERVAL 3 DAY)),

('Growth Marketing Manager', 'Drive user acquisition and engagement for our platform through data-driven marketing strategies.\n\nResponsibilities:\n• Develop growth marketing strategies\n• Manage paid advertising campaigns\n• Analyze marketing metrics and ROI\n• A/B test landing pages and messaging', 'Requirements:\n• 4+ years growth marketing experience\n• Proficiency in analytics tools\n• Experience with paid social and SEM\n• Strong analytical skills', 'San Francisco, CA', 'FULL_TIME', 'MID', 110000, 160000, 'USD', '2026-05-08', true, 8, @recruiter_id, DATE_SUB(NOW(), INTERVAL 5 DAY)),

('VP of Engineering', 'Lead our engineering organization of 200+ engineers. Set technical vision and build world-class teams.\n\nResponsibilities:\n• Lead multiple engineering teams\n• Define technical strategy and roadmap\n• Recruit and develop engineering talent\n• Partner with product and business leaders', 'Requirements:\n• 12+ years engineering experience\n• 5+ years in engineering leadership\n• Track record of building high-performing teams\n• Experience scaling organizations', 'Menlo Park, CA', 'FULL_TIME', 'EXECUTIVE', 280000, 450000, 'USD', '2026-06-01', true, 4, @recruiter_id, DATE_SUB(NOW(), INTERVAL 2 DAY)),

('Embedded Systems Engineer', 'Design firmware for our next-gen hardware products. Work at the intersection of software and hardware.\n\nResponsibilities:\n• Develop embedded firmware in C/C++\n• Design real-time control systems\n• Work with hardware design teams\n• Perform system testing and debugging', 'Requirements:\n• 4+ years embedded systems experience\n• Expert in C/C++ and RTOS\n• Experience with ARM processors\n• Knowledge of communication protocols (SPI, I2C, UART)', 'Redmond, WA', 'FULL_TIME', 'MID', 125000, 175000, 'USD', '2026-04-18', true, 2, @recruiter_id, DATE_SUB(NOW(), INTERVAL 9 DAY)),

('Remote Go Developer', 'Build high-performance microservices in Go for our distributed systems. Fully remote position.\n\nResponsibilities:\n• Design and build microservices in Go\n• Optimize for performance and concurrency\n• Write comprehensive tests\n• Participate in design reviews', 'Requirements:\n• 3+ years Go development experience\n• Experience with gRPC and protobuf\n• Knowledge of distributed systems\n• Strong understanding of concurrency', 'Remote', 'REMOTE', 'SENIOR', 140000, 200000, 'USD', '2026-05-10', true, 3, @recruiter_id, DATE_SUB(NOW(), INTERVAL 2 DAY));

-- Add skills to all jobs
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Senior Full Stack Engineer' AND s.name IN ('React', 'TypeScript', 'Node.js', 'AWS', 'Microservices', 'Docker');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Machine Learning Engineer' AND s.name IN ('Python', 'TensorFlow', 'PyTorch', 'Machine Learning', 'Data Science');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Frontend Developer' AND s.name IN ('React', 'TypeScript', 'JavaScript', 'HTML', 'CSS', 'Figma');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Cloud Solutions Architect' AND s.name IN ('AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Terraform');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Data Scientist' AND s.name IN ('Python', 'SQL', 'Machine Learning', 'Data Science');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Backend Engineer - Payments' AND s.name IN ('Java', 'Spring Boot', 'PostgreSQL', 'REST API', 'Microservices');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title LIKE 'Mobile Developer%' AND s.name IN ('React Native', 'JavaScript', 'TypeScript', 'Flutter');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'DevOps Engineer' AND s.name IN ('Docker', 'Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Linux', 'DevOps');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Product Designer (UX)' AND s.name IN ('Figma', 'UI/UX Design');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'E-commerce Platform Engineer' AND s.name IN ('Ruby on Rails', 'Node.js', 'React', 'PostgreSQL', 'REST API');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'AI Research Intern' AND s.name IN ('Python', 'PyTorch', 'Machine Learning', 'TensorFlow');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Remote Python Developer' AND s.name IN ('Python', 'Django', 'FastAPI', 'PostgreSQL', 'REST API');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Junior Software Engineer' AND s.name IN ('Java', 'Python', 'JavaScript', 'Git');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Part-Time UI Developer' AND s.name IN ('React', 'CSS', 'Tailwind CSS', 'Figma', 'JavaScript');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Contract Data Engineer' AND s.name IN ('Python', 'SQL', 'Kafka', 'AWS', 'DevOps');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Cybersecurity Analyst' AND s.name IN ('Linux', 'Python', 'AWS');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Site Reliability Engineer' AND s.name IN ('Python', 'Go', 'Kubernetes', 'Docker', 'Linux', 'AWS');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Technical Program Manager' AND s.name IN ('Agile', 'Scrum', 'Product Management');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'iOS Developer' AND s.name IN ('Swift', 'Git', 'REST API');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Android Developer' AND s.name IN ('Kotlin', 'Git', 'REST API');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Database Administrator' AND s.name IN ('MySQL', 'PostgreSQL', 'SQL', 'Linux', 'AWS');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'QA Automation Engineer' AND s.name IN ('Python', 'JavaScript', 'CI/CD', 'Git');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Blockchain Developer' AND s.name IN ('JavaScript', 'React', 'Blockchain', 'Web3');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Content Writer - Tech' AND s.name IN ('HTML', 'CSS', 'Git');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Staff Software Engineer' AND s.name IN ('Java', 'Python', 'Microservices', 'Kubernetes', 'AWS');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'ML Ops Engineer' AND s.name IN ('Python', 'Docker', 'Kubernetes', 'Machine Learning', 'AWS');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Growth Marketing Manager' AND s.name IN ('Data Science', 'SQL');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'VP of Engineering' AND s.name IN ('Agile', 'Scrum', 'Product Management');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Embedded Systems Engineer' AND s.name IN ('C++', 'C#', 'Linux', 'Git');
INSERT IGNORE INTO job_skills (job_id, skill_id) SELECT j.id, s.id FROM jobs j, skills s WHERE j.title = 'Remote Go Developer' AND s.name IN ('Go', 'Docker', 'Kubernetes', 'Microservices', 'REST API');
